apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payment-service-deployment
  name: payment-service-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-gateway
    spec:
      containers:
      - image: ssalami/payment-gateway
        name: payment-gateway
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  namespace: test
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082 
  selector:
    app: payment-gateway
  sessionAffinity: None

status:
  loadBalancer: {}
